image: mhart/alpine-node:14

stages:
  - lint
  - test

lint test:
  stage: lint
  script:
    - yarn install --progress=false
    - yarn run lint
  only:
    - production
    - test
    - dev

unit test:
  stage: test
  script:
    - yarn install --progress=false
    - yarn run test
