# BACK-END
FROM alpine/git

LABEL description="Image for back-end UpScience/LifeScience/JetScience project" \
      maintainer="Vladimir Orlov <vladimir.orlov@jetbrains.com>" \
      source="https://github.com/JetBrains/JetScience"

# config container
ENV APP_PORT 8080
ARG APP_PORT
EXPOSE $APP_PORT

WORKDIR /src

ARG GIT_USERNAME
ARG GIT_PASSWORD
RUN git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/JetBrains/JetScience.git

USER 33
FROM openjdk:11
WORKDIR /build
COPY --chown=33:33 --from=0 /src/JetScience/backend .

# build backend
RUN ./gradlew clean build -x check
# run backend
CMD ["java", "-Dserver.port=$APP_PORT", "-jar", "build/libs/backend-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=dev"]